apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret
  labels:
    app: {{ template "helm-guestbook.name" . }}
    chart: {{ template "helm-guestbook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  .secret-file: dmFsdWUtMg0KDQo=
